- kube.libsonnet
- tests/Makefile
- tests/golden/test-simple-validate.json
- tests/unittests.jsonnet
Many small diffs.
New features:
- Add `parseOctal` helper function (eg useful for volume `mode`).
- Add `toUpper` and `toLower`.
- Change `:` to `-` when preparing default `name` label (eg appears in
system object names but is not safe in label keys).
- Add `host` and `host_colon_port` helpers to `Service`.
- Set container `imagePullPolicy` default explicitly (following usual
k8s default logic). In particular this means the server-side value
will be updated if the jsonnet image is updated to/from `:latest`.
- Add `PodDisruptionBudget`.
- "First container" logic now defaults to the container named
`default` rather than _requiring_ a value for `default_container` in
the multi-container case. `default_container` continues to override.
- Add container `initContainers_`, similar to …
>  Update kube.libsonnet for newer (1.8+) k8s

- bitnami.libsonnet
- tests/golden/test-simple-validate.json
- tests/test-simple-validate.jsonnet
Followup from #7 by syncing it verbatim with internal one, closes #6.
> bitnami.libsonnet: update to jetstack/cert-manager annotations

- kube.libsonnet
First of all, thanks for the great library! We are using it in dozens of applications at Ecosia.org, and have built lots of whole application presets on top.
In some cases, we manually scale down deployments to zero replicas. I think it's totally valid to have the assert on the `replicas` field, but zero is also a valid value.
Also, we use the HPA to autoscale, and including the `replicas` field when using an HPA can lead to weird behaviour (see https://github.com/kubernetes/kubernetes/issues/25238). I added here a `hide_replicas` hidden field to the deploy spec, which will remote the `replicas` key from the spec (open to suggestions on a better way to do that - but I wanted to make it backwards-compatible for anyone who relies on the default being `replicas: 1`).
> Removes replicas assert

- kube.libsonnet
Fix #25
As reported in [the official Kubernetes docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class):
> A PV can have a class, which is specified by setting the storageClassName attribute to the name of a StorageClass. A PV of a particular class can only be bound to PVCs requesting that class. A PV with no storageClassName has no class and can only be bound to PVCs that request no particular class.
> In the past, the annotation `volume.beta.kubernetes.io/storage-class` was used instead of the `storageClassName` attribute. This annotation is still working, however it will become fully deprecated in a future Kubernetes release
> Fixed missing `storageClassName` field in PersistentVolumeClaim's `spec`

- kube.libsonnet
- tests/golden/test-simple-validate.json
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#deprecations-and-removals
mentions:
```
DaemonSet, Deployment, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 in v1.16. Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved via the apps/v1 API.
```
Also added the minimum supported version in the kube.libsonnet excplicitly.
> Update to require min k8s 1.9

- bitnami.libsonnet
- kube.libsonnet
- tests/golden/test-simple-validate.json
* bitnami.libsonnet: sync from internal (working, prod) repo
* kube.libsonnet:
- also add v1.16 Ingress apiVersio
- cap Deployment revisionHistoryLimit to 10
- NetworkPolicy: add required podSelector field
> [jjo] v1.16 Ingress apiVersion and other fixes

- Makefile
- README.md
- kube.libsonnet
- tests/.env
- tests/Dockerfile
- tests/Makefile
- tests/docker-compose.yaml
- tests/golden/test-simple-validate.json
* rollback Ingress apiVersion to extensions/v1beta1
for wider kubeapi versions support:
- networking.k8s.io/v1beta1: only available since v1.14
- extensions/v1beta1: available until v1.20
* add docker-compose'd e2e testing via k3s dummy container
for kube-api serving defaulting to v1.13, would have caught
#27 issue as noted at #22
> [jjo] rollback Ingress apiVersion, better testing

- .gitattributes
- README.md
- kube.libsonnet
- tests/Makefile
- tests/docker-compose.yaml
- tests/golden/init-kube.json
- tests/golden/test-simple-validate.json
- tests/init-kube.jsonnet
- tests/k3s-e2e-test.sh
- tests/test-simple-validate.jsonnet
* kube-libsonnet: add `VerticalPodAutoscaler` (aka VPA), and
`createVPAFor` helper function
* tests/test-simple-validate.jsonnet: add VPA coverage
* tests/docker-compose.yaml: move embedded bash script to
tests/k3s-e2e-test.sh
* Makefile: adjust e2e-tests, in particular as VPAs are CRs, need to
initialize the dockerized k3s run with VPA CRD
(tests/init-kube.jsonnet )
> [jjo] add VerticalPodAutoscaler, adjust e2e-tests

- kube.libsonnet
- tests/.env
- tests/Dockerfile
- tests/Makefile
- tests/docker-compose.yaml
- tests/golden/test-simple-validate.json
Fixes #32.
* Ingress: use networking.k8s.io/v1beta1 apiVersion: deprecated on
v1.18+, available since v1.14
* rework e2e testing to cover several releases, see
$ grep E2E_K3S_VERSIONS= tests/Makefile
E2E_K3S_VERSIONS=$(K3S_V1_14) $(K3S_V1_15) $(K3S_V1_16) $(K3S_V1_17)
* e2e testing now shows tested releases:
SUCCESS: verified Kubernetes versions:
Server Version: v1.14.5-k3s.1
Server Version: v1.15.4-k3s.1
Server Version: v1.16.3-k3s.2
Server Version: v1.17.2+k3s1
> [jjo] Ingress: use networking.k8s.io/v1beta1 apiVersion

- kube.libsonnet
- tests/golden/test-simple-validate.json
- tests/test-simple-validate.jsonnet
- tests/unittests.jsonnet
- utils.libsonnet
* `kube.libsonnet`: few bits here&there, notable adding `name`
field to svc ports
* `utils.libsonnet`: copied verbatim and added unittests
> [jjo] merge kube-libsonnet bits from bitnami/kube-prod-runtime

- kube-platforms.libsonnet
- kube.libsonnet
- tests/golden/test-gke-ManagedCertificate.pass.json
- tests/test-gke-ManagedCertificate.fail.jsonnet
- tests/test-gke-ManagedCertificate.pass.jsonnet
Adds missing objects `ManagedCertificate` and `BackendConfig`, scoped to `gke::` namespace
```
my_cert: kube.gke.ManagedCertificate("my-cert") {
spec+: {
domains: ["foo.example.com"],
},
}
```
```
my_cert: kube.gke.BackendConfig("config") {
spec+: {
cdn: {
enabled: true
},
},
}
```
> Add ManagedCertificates and Backend Config objects

- tests/unittests.pass.jsonnet
Fix typo in HashedSecret negative test so that the test fails for the right reason :P
> Fix typo in HashedSecret negative test

- bitnami.libsonnet
- tests/golden/test-simple-validate.pass.json
- tests/init-kube.jsonnet
- tests/test-simple-validate.pass.jsonnet
Improve cert-manager support in bitnami.libsonnet:
* add CertManager section (field) with all needed bits
* add CertManager.InCluster.Certificate() function to ease
issuing in-cluster certs
* move many Ingress related bits under CertManager field,
remove old cruft
> [jjo] feat: improve cert-manager support

- tests/Makefile
Signed-off-by: David Barranco <dbarranco@vmware.com>
```
docker-compose -p kubelibsonnet down
Stopping k3s-api ... done
Removing e2e-test ... done
Removing k3s-api  ... done
Removing network kubelibsonnet_default
rm -rf ././tmp-rancher/root
SUCCESS: verified Kubernetes versions:
Server Version: v1.14.5-k3s.1
Server Version: v1.15.4-k3s.1
Server Version: v1.16.3-k3s.2
Server Version: v1.17.2+k3s1
Server Version: v1.18.2+k3s1
Server Version: v1.19.2+k3s1
```
> Feat: Increase tests coverage - k3s-1.19

- kube.libsonnet
- tests/golden/test-simple-validate.pass.json
- tests/test-simple-validate.pass.jsonnet
These can be rules that map different hostnames to backends, where each
backend handles all paths, so has no `path` field. For example:
```
spec:
rules:
- host: a.example.com
http:
paths:
- backend:
serviceName: service-a
servicePort: web
- host: b.example.com
http:
paths:
- backend:
serviceName: service-b
servicePort: web
```
Currently this fails with:
```
RUNTIME ERROR: Field does not exist: path
kube-libsonnet/kube.libsonnet:588:26-32	thunk from <object <anonymous>>
```
> Allow specifying Ingress rules with http.paths with no path.

- bitnami.libsonnet
- kube.libsonnet
- tests/Makefile
- tests/golden/test-simple-validate.pass.json
- tests/init-kube.jsonnet
- tests/test-simple-validate.pass.jsonnet
Fixes #60.
Support Kubernetes v1.22+ apiVersions deprecations, notably:
* `Ingress`:
- use `apiVersion: networking.k8s.io/v1`
- create (and populate) `service` field to each `path`
(previously `serviceName` and `servicePort`)
- `bitnami.libsonnet`: use `pathType: ImplementationSpecific`, which seems to be the
most generic one
* `CustomResourceDefinition`:
- use `apiVersion: apiextensions.k8s.io/v1`
- create `versions` map with sensible defaults, including `spec`
field, as commonly used fro CRs
Other changes:
* `tests/Makefile`: support (only) v1.19+
* `tests/init-kube.jsonnet`: CRD tweaks
FYI this is on top of #59.
**NOTE**: once merged upstream, would strongly recommend tagging it as `v1.19.0`, following the convention that tags' `<major>.<minor>` should express minimum required …
> [jjo] support Kubernetes v1.22+ apiVersions deprecations

- bitnami.libsonnet
- kube.libsonnet
- tests/Makefile
- tests/golden/test-simple-validate.pass.json
- tests/init-kube.jsonnet
- tests/test-simple-validate.pass.jsonnet
Reverts bitnami-labs/kube-libsonnet#61
It seems that #61 is going to cause some issues with our already existing Ingresses.
I've tested some new Ingresses in a 1.19 kops-based Kubernetes cluster and found-out the following:
```
....
[spec.rules[0].http.paths[0].backend: Invalid value: "": cannot set both port name & port number
And the Ingress resource I'm testing is:
```
```
...
- host: <omitted>
http:
paths:
- backend:
service:
name: <omitted>
port:
name: http
number: 8080
path: /
pathType: ImplementationSpecific
```
Checking-out the official docs, it seems they also stopped adding the port number and name:
```
spec:
rules:
- http:
paths:
- path: /testpath
pathType: Prefix
backend:
service:
name: test
port:
number: 80
``` …
> Revert "[jjo] support Kubernetes v1.22+ apiVersions deprecations"

- bitnami.libsonnet
- kube.libsonnet
- tests/Makefile
- tests/golden/test-Ingress-2ndport.pass.json
- tests/golden/test-Ingress-port_num_only.pass.json
- tests/golden/test-simple-validate.pass.json
- tests/init-kube.jsonnet
- tests/test-Ingress-2ndport.pass.jsonnet
- tests/test-Ingress-name_port.fail.jsonnet
- tests/test-Ingress-port_num_only.pass.jsonnet
- tests/test-simple-validate.pass.jsonnet
Fixes #60, after also fixing PR #61 issues.
Support Kubernetes v1.22+ apiVersions deprecations, notably:
* `Ingress`:
- use `apiVersion: networking.k8s.io/v1`
- create (and populate) `service` field to each `path`
(previously `serviceName` and `servicePort`)
- `bitnami.libsonnet`: use `pathType: ImplementationSpecific`, which seems to be the
most generic one
- add Ingress service `name` and `number` mutual exclusion logic and test cases
* `CustomResourceDefinition`:
- use `apiVersion: apiextensions.k8s.io/v1`
- create `versions` map with sensible defaults, including `spec`
field, as commonly used fro CRs
Other changes:
* `tests/Makefile`: support (only) v1.19+
* `tests/init-kube.jsonnet`: CRD tweaks
> [jjo] support Kubernetes v1.22+ apiVersions deprecations (round2)

- kube.libsonnet
The storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass,
and VolumeAttachment is no longer served as of v1.22.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#storage-resources-v122
Signed-off-by: Lionel Hubaut <lionel.hubaut@tessares.net>
> kube-libsonnet: remove deprecated api.

- kube.libsonnet
Adding an annotation is deprecated and will no longer be available in the later version of K8s, hence it's better to remove it https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class
`storageClassName` attribute is enough to set the name of the Storage Class, so this annotation is unnecessary
PS: force-push was for getting commits signed with my right GPG keys
> remove deprecated annotation from pvc manifest

- kube.libsonnet
- tests/golden/test-Service-container_index.pass.json
- tests/test-Service-container_index.fail.jsonnet
- tests/test-Service-container_index.pass.jsonnet
The current helper only works for the first container, having this index hidden variable allows us to expose services from a second sidecar type container in the same pod.
> add container_index for service object

- kube.libsonnet
This PR removes the `replicas: 1` inside the Deployment object.
For Horizontal Pod Autoscaler to work properly with gitops systems such as ArgoCD, FluxCD, Deployment objects shouldnt' have `replicas` set. The default `replicas` is 1 so this is safe to be removed.
Also it appears that it is not easy to remove a field in jsonnet once it is set, so it is better to just not set it.
* Linked issue: https://github.com/bitnami-labs/kube-libsonnet/issues/58
* ArgoCD: https://argo-cd.readthedocs.io/en/stable/user-guide/best_practices/#leaving-room-for-imperativeness
* FluxCD: https://argo-cd.readthedocs.io/en/stable/user-guide/best_practices/#leaving-room-for-imperativeness
* Remove a field from jsonnet issue: https://github.com/google/jsonnet/issues/312
> Deployment: remove replicas=1
